window.AJONTE_DEVOTIONALS = [
  {
    date: "2026-09-25",
    displayDate: "September 25, 2026",
    title: "You Become What You Behold",
    reference: "2 Corinthians 3:17–18",
    translation: "LEB",
    verse: "And we all, with unveiled face, reflecting the glory of the Lord, are being transformed into the same image from glory to glory, just as from the Lord, the Spirit.",
    body: [
      "There is something powerful about standing beneath the radiance of the sun.",
      "You do not create its light. You do not command it to shine. You simply turn toward something far greater than yourself and allow its warmth and brilliance to fall upon you.",
      "Sanctification is something like that.",
      "The Christian life is not merely God handing us a list of rules and telling us to imitate Him from a distance. It is transformation through continually beholding His glory.",
      "What you behold begins to shape you.",
      "When you continually look toward God—through His Word, His ways, His character, and ultimately through Christ—His glory begins correcting your vision.",
      "You start seeing love differently because you have seen His love.",
      "You understand justice differently because you have witnessed His justice.",
      "You begin recognizing holiness because you have encountered His purity.",
      "You learn forgiveness by beholding the One who forgave His enemies.",
      "You learn humility by looking at the King who washed the feet of His disciples.",
      "You learn obedience by beholding the Son who submitted Himself completely to the Father.",
      "God’s glory is not merely brightness. His glory is the fullness of who He is.",
      "It is revealed in His words, His ways, His wisdom, His precepts, His mercy, His holiness, and His truth. As we behold those things, the Holy Spirit renews our minds and transforms us into the image we are seeing.",
      "That transformation does not happen all at once.",
      "Paul says we are transformed ‘from glory to glory.’",
      "One degree at a time.",
      "One revelation at a time.",
      "One surrendered thought at a time.",
      "One act of obedience at a time.",
      "God reveals something about Himself, and that revelation changes how we understand everything else.",
      "When He teaches us about His faithfulness, it changes how we endure uncertainty.",
      "When He reveals His mercy, it changes how we respond to someone who has wronged us.",
      "When He reveals His holiness, it changes what we are willing to tolerate within ourselves.",
      "When He reveals His patience, it changes how we treat people who are still growing.",
      "When He reveals His sovereignty, it changes how tightly we feel the need to control our lives.",
      "God is the source of everything, so learning about Him eventually unfolds into every part of creation and every area of life. His glory teaches us how to see relationships, suffering, beauty, work, truth, responsibility, forgiveness, and love.",
      "To know Him more deeply is to begin seeing everything else more clearly.",
      "And because God is infinite, we will never reach the end of His glory.",
      "There will never be a moment in this life when we can say, ‘I have seen everything there is to see of God.’",
      "Every revelation opens into another.",
      "Every answer reveals a greater mystery.",
      "Every glimpse of His beauty invites us deeper.",
      "The Christian life is therefore a life-changing adventure in which God is continually revealing Himself, and every new revelation gives the Holy Spirit something new to form within us.",
      "We are always learning.",
      "Always thinking.",
      "Always surrendering.",
      "Always being renewed.",
      "Always moving from glory to glory.",
      "This is why our attention matters so much.",
      "If I continually behold anger, fear, envy, lust, pride, division, or the approval of the world, those things will begin shaping how I think and live.",
      "But if I continually turn my attention toward Christ, His character begins becoming the pattern of my own.",
      "Sanctification is not accomplished by staring endlessly at everything wrong with me.",
      "It happens as I turn toward the One who is right.",
      "I do not overcome darkness by becoming fascinated with the darkness. I overcome it by continually returning to the light.",
      "Physically, we cannot endure staring directly into the sun. Its radiance is too great for our eyes. Yet through Jesus Christ, God has made His glory approachable.",
      "Christ is ‘the radiance of His glory and the representation of His essence.’",
      "In the face of Jesus Christ, we behold the glory of God—and instead of that glory destroying us, the Spirit uses it to transform us.",
      "So I keep looking toward Jesus.",
      "I behold the way He speaks.",
      "I behold the way He loves.",
      "I behold the way He forgives.",
      "I behold the way He handles betrayal.",
      "I behold the way He confronts evil.",
      "I behold the way He submits to the Father.",
      "I behold the way He gives Himself for others.",
      "And as I remain there, looking toward His glory, the Spirit gradually makes His ways my ways.",
      "His thoughts begin renewing my thoughts.",
      "His desires begin reshaping my desires.",
      "His love begins flowing through my life.",
      "His image becomes increasingly visible within me.",
      "I am not creating the light.",
      "I am simply turning toward it.",
      "And as I behold the glory of the Lord, I am being transformed into the same image—from glory to glory."
    ],
    reflection: "What has been holding my attention long enough to shape me—and what part of Christ’s character is the Holy Spirit inviting me to behold until it becomes visible in my own life?"
  },
  ...(window.AJONTE_DEVOTIONALS || [])
];
