window.AJONTE_DEVOTIONALS = [
  {
    date: "2026-08-26",
    displayDate: "August 26, 2026",
    title: "Abide in Him",
    reference: "John 15:4–5",
    translation: "LEB",
    verse: "Remain in me, and I in you. Just as the branch is not able to bear fruit by itself unless it remains in the vine, so neither can you unless you remain in me. I am the vine; you are the branches…",
    body: [
      "To remain in Christ is to abide in Him.",
      "To dwell with Him and let Him dwell in you. To live with His Word before you until the fruit of your thoughts, your beliefs, your desires, and eventually your life begins to revolve around Him.",
      "A branch bears the nature of what it is connected to.",
      "So if Christ is the vine and we are the branches, then the life flowing through us should increasingly look like Christ.",
      "That means keeping the things of God before your mind. Thinking on His Word. Seeing life through His kingdom. Learning to have the mind of Christ until His ways become the way you naturally begin to see things.",
      "This is not about trying to manufacture righteousness through legalism.",
      "It is about living in the Spirit.",
      "You stop thinking like the world because you are abiding somewhere else. You stop allowing the world to determine what is good, what is true, what is valuable, and what life is supposed to look like because your mind is dwelling in another kingdom.",
      "Remain in Me, and I in you.",
      "Let Christ abide in you, and you abide in Christ.",
      "When Christ is in you, fruit follows.",
      "You begin to think differently. Believe differently. Desire differently. Live differently.",
      "You become kingdom-minded because you are abiding in the King."
    ],
    reflection: "What am I abiding in long enough for it to shape the way I think, believe, and live?"
  },
  {
    date: "2026-08-24",
    displayDate: "August 24, 2026",
    title: "Walk in What Has Been Revealed",
    reference: "Isaiah 30:21",
    translation: "LEB",
    verse: "And your ears shall hear a word from behind you, saying, ‘This is the way; walk in it,’ when you go to your right and when you go to your left.",
    body: [
      "There is a responsibility that comes with revealed truth.",
      "God does not have to bring us His revelations. He does not have to give us His oracles. He does not have to make His ways known to us. So when He does reveal something, it is not just so we can say we know more. It is not for knowledge’s sake alone.",
      "It is so that we can walk in it.",
      "Once God has made something known, then there is a responsibility on us to begin moving in that direction. We can no longer say we did not know. We have been shown the way, and now the question becomes whether we are going to walk in what has been revealed.",
      "And I think that is what makes this verse so beautiful, because as we begin walking in the things God has shown us, we hear the Father lovingly guiding us further into the things of Him.",
      "He says, ‘This is the way; walk in it.’",
      "And then when we start drifting to the right or to the left, there is still a voice there. The Father is still guiding.",
      "That matters because a father knows when a child is learning something that goes against the child’s nature. He knows when something is difficult for them. He knows when their instincts are pulling them one way, but he is teaching them another way.",
      "A good father does not guide that child in a punishing way. He understands that they are learning.",
      "He corrects them while they are moving. He says, ‘No, not that way. Come back this way.’ He is not shocked every time they take a wrong step. He knows the thing he is teaching them is not yet natural to them.",
      "And I think God deals with us the same way.",
      "There are things in God that go directly against our fallen nature. There are ways of thinking, ways of loving, ways of forgiving, ways of obeying, ways of denying ourselves that are not natural to us.",
      "So He has to teach us how to walk in them.",
      "That does not remove our responsibility. Once He reveals the truth, we are responsible to begin walking.",
      "But it also means the walk is not ours to perfect by ourselves.",
      "We take the step, and while we are taking it, the Father is still there. Still speaking. Still correcting. Still guiding us further into Himself.",
      "And that is why revelation should never become something we collect.",
      "God is not showing us truth so that we can admire how much we know. He is showing us truth so that our lives can begin to look like what He has revealed.",
      "The purpose of the oracle is the walk. The purpose of knowing the way is to begin walking in it.",
      "And as we walk, we learn to recognize that loving voice behind us saying: ‘This is the way. Walk in it.’"
    ],
    reflection: "What truth has God already revealed to me that I am responsible to begin walking in?"
  },
  {
    date: "2026-08-23",
    displayDate: "August 23, 2026",
    title: "When Understanding Has to Bow",
    reference: "Proverbs 3:5–6",
    translation: "LEB",
    verse: "Trust in Yahweh with all your heart, and do not rely on your own understanding. In all your ways acknowledge him, and he will make your paths straight.",
    body: [
      "To trust in Yahweh with all your heart is to put the full weight of yourself on what He has said and on who He has shown Himself to be.",
      "There is something childlike about that kind of faith. A small child believes his father because, at that stage of life, his father is one of the primary measures by which he understands what is true. He does not possess enough knowledge to evaluate everything for himself. He trusts the one he knows.",
      "That seems to be the posture Proverbs is calling us toward with God.",
      "Believe what Yahweh says. Believe what Yahweh has revealed about Himself. And when what He has said collides with what you presently understand, do not make your understanding the final authority.",
      "Jesus gives us an extraordinary picture of this in Gethsemane. He knew what obedience to the Father was about to cost Him. He prayed concerning the cup before Him, yet submitted Himself to the Father's will. The immediate human experience of suffering did not become the final judge of what should be done. The Father had already revealed the path: the suffering servant, the Lamb given for the salvation of others.",
      "There are moments when obedience will make less sense to us than the alternative. That is where trust becomes more than agreement.",
      "If I only obey God when His instructions already make sense to me, then I am not ultimately relying upon God. I am relying upon my understanding and allowing God to agree with it.",
      "But Scripture says: ‘Do not rely on your own understanding.’",
      "Then comes the comprehensiveness of the next command: ‘In all your ways acknowledge him.’ All means all.",
      "God is not meant to become one portion of life alongside career, relationships, pleasure, money, thought, and ambition. He is the center from which all of those things are ordered.",
      "I once encountered the picture of the Christian life as being eccentric in the literal sense—having a different center. Christ becomes the center of the wheel, and everything else becomes a spoke extending from Him. Nothing is permitted to establish an independent center of its own.",
      "So in every way, acknowledge Him. Before I decide what is good, what does my Father call good? Before I decide which direction is right, what resembles His ways? Before I trust my interpretation of a circumstance, what has He already said?",
      "And then comes one of the most comforting parts of the passage: ‘He will make your paths straight.’ Notice that it does not say that you will perfectly straighten your own path.",
      "Imagine a child genuinely trying to follow his father. He will misunderstand sometimes. He will stumble. He will take an awkward step. But a good father who sees that child walking with him does not stand at the destination waiting for the child to somehow figure everything out alone. He corrects him as they go.",
      "That is what makes our obedience participatory rather than self-saving. We walk. We listen. We trust. We respond. But God gives the growth. God corrects. God redirects. God straightens the path.",
      "There are moments when faith feels like a child standing somewhere high while his father tells him to take the next step. The child may not understand the mechanics of what is happening. He only knows the person telling him to move.",
      "He takes the step because he knows his father is there. That is trust. Not knowing that you will never stumble, but knowing who is with you if you do.",
      "So keep walking. Your confidence does not have to rest in your ability to perfectly understand the road. It can rest in the Father who knows the road, walks it with you, and is able to straighten you as you go."
    ],
    reflection: "When God’s revealed will and my present understanding disagree, which one am I actually allowing to carry the weight of my life?"
  },
  {
    date: "2026-08-22",
    displayDate: "August 22, 2026",
    title: "Knowing the Ways of the Father",
    reference: "Psalm 25:4–5",
    translation: "LEB",
    verse: "Make me know your ways, O Yahweh; teach me your paths. Guide me in your truth and teach me, for you are the God of my salvation; I wait for you all day long.",
    body: [
      "When you know your father, you begin to know his ways. You know what he considers good. You know what he considers wrong. You know what kind of decision sounds like him and what kind does not.",
      "If someone came to you and said, ‘I heard your father likes this,’ and you knew that completely contradicted his character, you would be able to say, ‘No. My father is not like that.’",
      "That kind of knowledge does not come from knowing facts about a person. It comes from relationship. You have talked with him. Walked with him. Watched how he responds. Over time, you begin to recognize his ways.",
      "So when David says, ‘Make me know your ways, O Yahweh,’ he is asking for more than information. He wants to know God well enough that the character of God becomes recognizable to him.",
      "Then he says, ‘Teach me your paths. Guide me in your truth and teach me.’ Why does God have to guide us into His truth? Because His ways are higher than our ways. His thoughts are higher than ours. What seems natural to us is not always what is righteous, because our own nature has been bent by sin. There are truths of God that we would not naturally arrive at by following ourselves.",
      "So He must teach us.",
      "He does that through His Word. He reveals what is true, what is good, what is righteous, and what kind of life reflects His character. And even after revealing it, we still need Him to guide us into actually walking it.",
      "David continues: ‘For you are the God of my salvation.’ If there is any hope of being saved, redeemed, enlightened, restored, or made whole, it has to come from God. We cannot lead ourselves into salvation. We cannot reason ourselves into holiness. We cannot transform our own hearts by force.",
      "God must lead us down that path.",
      "And that makes the final statement difficult: ‘I wait for you all day long.’ Waiting is the posture of someone who has accepted that God is the one doing the deepest work.",
      "We often want to rush ahead. We want immediate understanding, immediate change, immediate answers. But if God is the teacher, then we have to remain teachable. If God is the guide, then we cannot keep running ahead of Him.",
      "Sometimes faithfulness looks like movement. Sometimes faithfulness looks like waiting long enough for the Father to show us the way."
    ],
    reflection: "Do I know God well enough to recognize His ways, and am I willing to wait for Him when I do not yet know the path?"
  },
  {
    date: "2026-08-21",
    displayDate: "August 21, 2026",
    title: "The Path Where God Walks",
    reference: "Psalm 16:11",
    translation: "LEB",
    verse: "You will make known to me the path of life. In your presence is fullness of joy. At your right hand are pleasures forever.",
    body: [
      "Every man has a way he would naturally choose for himself. We have our own bent, our own instincts, our own idea of what life ought to look like. Left completely to ourselves, we will find a road and begin walking it.",
      "But at some point, God invades that journey with revelation.",
      "David says, ‘You will make known to me the path of life.’ The path is not something he invents. It has to be made known to him. God reveals that there is a way of living that leads toward life, and then He instructs us in how to walk it.",
      "That is one of the ways I think about Torah—God's instruction. Torah does not literally mean ‘the path,’ but God's instruction establishes the boundaries of the path. It tells us where life is meant to be lived. The law was never evidence that man could perfectly walk the way by his own strength; it was revelation from God saying, ‘This is the way. Walk here.’",
      "God's precepts are therefore not disconnected from God Himself. When Scripture calls us to believe Him, trust His commands, and walk in His ways, those ideas belong together. His precepts reveal His character and mark out the kind of place in which fellowship with Him can flourish.",
      "You see a picture of this in Israel's camp. God repeatedly commanded Israel to keep the camp from defilement because He walked among them. His presence was in their midst, and the place where God dwelt was to be prepared for Him.",
      "That changes the way I hear the next line: ‘In your presence is fullness of joy.’",
      "Where is His presence encountered? On the path He has revealed.",
      "The boundaries are not there to keep us away from joy. They mark the place where joy is found. God teaches us His ways because He is leading us into the kind of life in which we can increasingly recognize, enjoy, and walk with Him.",
      "Then David says, ‘At your right hand are pleasures forever.’ Those pleasures are deeper than whatever temporary satisfaction the world can offer. There is joy. Hope. Love. Wisdom. Revelation. Understanding. The quiet excitement of God showing you something you had never seen before. The experience of being led further into Him and realizing there is still more.",
      "There are pleasures forever because there is no end to God.",
      "Life with Him is not an empty road marked only by restrictions. The boundaries reveal a path, the path leads into His presence, and in His presence we discover that holiness was never the enemy of pleasure. It was the road to the deepest kind of it."
    ],
    reflection: "Am I asking God to bless the path I have chosen, or am I allowing Him to make the path of life known to me?"
  }
];
