window.AJONTE_DEVOTIONALS = [
  {
    date: "2026-09-08",
    displayDate: "September 8, 2026",
    title: "The Spirit of Adoption",
    reference: "Romans 8:14–16",
    translation: "LEB",
    verse: "For all those who are led by the Spirit of God, these are sons of God. For you have not received a spirit of slavery leading to fear again, but you have received the Spirit of adoption, by whom we cry out, ‘Abba! Father!’ The Spirit himself confirms to our spirit that we are children of God,",
    body: [
      "The Spirit does not merely make you useful to God. He teaches you that you belong to God.",
      "Paul says that those who are led by the Spirit of God are sons of God.",
      "That changes the way I think about being led.",
      "You are not following God like an employee trying to keep a position. You have received the Spirit of adoption.",
      "You cry, ‘Abba! Father!’",
      "Before the Spirit teaches you what assignment to complete, He establishes whose child you are.",
      "And I think that matters because a child who knows he belongs can be corrected without believing correction means rejection.",
      "He can fail while learning his Father's ways and still come back to his Father.",
      "He can admit weakness. He can ask questions. He can learn obedience without acting like every mistake has put him outside of the house.",
      "The Spirit is not only telling you what God wants. He is teaching you how your Father walks.",
      "And the more you know the Father, the more recognizable His ways become.",
      "The more recognizable His ways become, the easier it becomes to notice when the Spirit is leading you toward something that looks like Him.",
      "That is what sonship should begin producing.",
      "Eventually there should be something of the Father visible in the child.",
      "Not because the child earned the family name.",
      "Because he bears it.",
      "So being led by the Spirit is not merely about getting instructions from God. It is learning to walk through this world as someone who knows who his Father is and knows that he belongs to Him."
    ],
    reflection: "Am I following God like someone trying to earn a place in His house, or like a son who already belongs there and is learning to walk like his Father?"
  },
  {
    date: "2026-09-07",
    displayDate: "September 7, 2026",
    title: "He Will Glorify Christ",
    reference: "John 16:13–14",
    translation: "LEB",
    verse: "But when he—the Spirit of truth—comes, he will guide you into all the truth. For he will not speak from himself, but whatever he hears he will speak, and he will proclaim to you the things to come. He will glorify me, because he will take from what is mine and will proclaim it to you.",
    body: [
      "Jesus says something very clear about the Holy Spirit: ‘He will glorify me.’",
      "That tells you something about the work of the Spirit.",
      "The Spirit is not drawing you deeper into yourself. He is revealing Christ.",
      "He teaches you what belongs to Christ. He brings His words back before you. He guides you into truth.",
      "And then that truth begins doing something in you.",
      "It changes what you believe. What you believe begins changing what you desire. What you desire begins changing how you live.",
      "Eventually the Christ the Spirit has been revealing to you should begin becoming visible through you.",
      "That is why spiritual growth should always make Christ larger in your eyes, not you.",
      "If I grow in wisdom, that wisdom should point back to Christ.",
      "If I grow in strength, that strength should point back to Christ.",
      "If fruit begins appearing in my life, that fruit should look like Christ.",
      "Jesus says the Spirit will glorify Him.",
      "So if something is really coming from the Spirit, the end result should not be me becoming more impressed with myself.",
      "It should be Christ becoming more beautiful, more real, and more visible.",
      "And I love that Jesus says the Spirit will guide us into truth.",
      "A guide assumes movement.",
      "The Spirit does not just hand you information and leave you standing there. He leads you further.",
      "Truth becomes a path again.",
      "God reveals the way, gives you His Spirit, and then the Spirit walks with you into what God has revealed.",
      "He does not merely point toward the road.",
      "He comes with you."
    ],
    reflection: "If the work of the Holy Spirit is to glorify Christ, is the spiritual growth happening in my life making people more impressed with me—or making Christ easier to see?"
  },
  {
    date: "2026-09-06",
    displayDate: "September 6, 2026",
    title: "Strength in Weakness",
    reference: "2 Corinthians 12:9–10",
    translation: "LEB",
    verse: "And he said to me, ‘My grace is sufficient for you, because the power is perfected in weakness.’ Therefore rather I will boast most gladly in my weaknesses, in order that the power of Christ may reside in me. Therefore I delight in weaknesses, in insults, in calamities, in persecutions and difficulties for the sake of Christ, for whenever I am weak, then I am strong.",
    body: [
      "Paul wanted the weakness removed.",
      "He asked God to take it away.",
      "And God's answer was, ‘My grace is sufficient for you.’",
      "That is difficult because we naturally think maturity means eventually becoming strong enough that we do not need help anymore.",
      "But the Christian life keeps teaching you the opposite.",
      "You grow, but your growth keeps showing you how much you need God.",
      "Paul says the power is perfected in weakness.",
      "So weakness is not always the thing stopping God from using you.",
      "Sometimes it is the place where His strength becomes the clearest.",
      "There are places in your life where you may keep thinking, ‘Once I finally get stronger here, then God can use me.’",
      "But maybe God is saying, ‘I can use you here, because here you know you need Me.’",
      "Your lack of wisdom can make you seek His wisdom.",
      "Your fear can make you depend on His courage.",
      "Your inability to change yourself can make you cling to the Spirit who actually changes people.",
      "And when strength comes through a place where you know you were weak, there is very little confusion about where that strength came from.",
      "That is why Paul can say, ‘Whenever I am weak, then I am strong.’",
      "He is not glorifying weakness.",
      "He has just learned where strength actually comes from.",
      "Maybe maturity is not getting to the point where you can finally tell God, ‘I can take it from here.’",
      "Maybe maturity is realizing more deeply, ‘Apart from You, I never could.’"
    ],
    reflection: "What weakness am I still asking God to remove because I think it disqualifies me, when He may be teaching me to depend upon His strength precisely there?"
  },
  {
    date: "2026-09-05",
    displayDate: "September 5, 2026",
    title: "The Treasure and the Vessel",
    reference: "2 Corinthians 4:7",
    translation: "LEB",
    verse: "But we have this treasure in earthenware jars, in order that the extraordinary degree of the power may be from God and not from us.",
    body: [
      "Paul calls us earthenware jars.",
      "And I think there is something important in that.",
      "The value of the jar is not primarily the jar. It is what the jar is carrying.",
      "We keep coming back to this: Christ lives in you. His Spirit produces the fruit. God gives the growth. His glory becomes visible through your life.",
      "But Scripture keeps making sure the glory goes back to the right place.",
      "‘That the extraordinary degree of the power may be from God and not from us.’",
      "God is not embarrassed by the fact that the vessel is ordinary.",
      "Sometimes the weakness of the vessel makes the treasure easier to recognize.",
      "If patience comes through me and I know how impatient I naturally am, I know where it came from.",
      "If wisdom comes through me beyond what I knew, I know where it came from.",
      "If I have courage in a place where I know I was afraid, I know where it came from.",
      "The jar did not create the treasure.",
      "And Christian humility is not pretending nothing good is happening through your life.",
      "It is being truthful about the source.",
      "You do not have to deny the fruit. You just cannot claim to be the root.",
      "You do not have to act like the light is not beautiful. You just remember you are reflecting it.",
      "So do not spend your life trying to make the vessel look extraordinary.",
      "Carry the treasure well.",
      "And when people see something glorious through your life, give credit to whom credit is due."
    ],
    reflection: "When something beautiful comes through my life, am I trying to make the vessel look impressive—or am I living in such a way that people can recognize the treasure I am carrying?"
  },
  {
    date: "2026-09-04",
    displayDate: "September 4, 2026",
    title: "God Gives the Growth",
    reference: "1 Corinthians 3:6–7",
    translation: "LEB",
    verse: "I planted, Apollos watered, but God was causing [it] to grow. So then, neither the one who plants nor the one who waters is anything, but God who is causing [it] to grow.",
    body: [
      "Paul planted. Apollos watered. God caused the growth.",
      "All three parts matter, but they are not the same responsibility.",
      "You are responsible for faithfulness.",
      "You are not responsible for being God.",
      "You can plant truth in somebody's life. You can encourage them, teach them, love them, correct them, pray for them.",
      "You can water something somebody else planted.",
      "But you cannot reach inside another person and make the seed grow.",
      "That belongs to God.",
      "And I think the same thing is true in our own lives.",
      "You put Scripture in front of yourself. You pray. You obey. You discipline yourself. You keep returning your mind to Christ.",
      "That is planting and watering.",
      "But when something that used to control you loses its power, who gave the growth?",
      "When patience begins showing up where anger used to live, who gave the growth?",
      "When truth you used to fight becomes something you love, who gave the growth?",
      "God did.",
      "That keeps us from being passive, because Paul really planted and Apollos really watered.",
      "But it also keeps us from pride, because neither one could create life.",
      "And it changes the way you love people.",
      "Sometimes God only asks you to plant something in a person that you may never personally see grow.",
      "You may speak one true sentence and somebody else waters it years later.",
      "Your job was not to manufacture the harvest.",
      "Your job was to be faithful with the seed God put in your hand."
    ],
    reflection: "Where have I been judging my faithfulness by whether I could produce the outcome, when God may only have asked me to plant or water and trust Him with the growth?"
  },
  {
    date: "2026-09-03",
    displayDate: "September 3, 2026",
    title: "God Is Working in You",
    reference: "Philippians 2:12–13",
    translation: "LEB",
    verse: "Therefore my dear friends, just as you have always obeyed, not as in my presence only but now much more in my absence, work out your own salvation with fear and trembling. For the one at work in you, both to will and to work for his good pleasure, is God.",
    body: [
      "Paul tells you to work, and then immediately tells you who is working in you.",
      "‘For the one at work in you, both to will and to work for his good pleasure, is God.’",
      "That is the Christian life.",
      "You participate in what God is producing.",
      "You obey. You discipline yourself. You make decisions. You actually walk.",
      "But underneath all of that, God is doing a work in you that you could not manufacture by yourself.",
      "And I think the part that stands out most is that He works in you ‘to will and to work.’",
      "God is not only changing what you do.",
      "He is changing what you want.",
      "At first obedience can feel like, ‘God wants this, but I want that.’",
      "But as He renews the mind and changes the heart, you begin getting to another place.",
      "‘God wants this, and I am beginning to want what He wants.’",
      "That is a deeper transformation.",
      "You are not only forcing your hands to do something your heart hates.",
      "God is working until your desires begin agreeing with Him.",
      "So when you work out what God is working in, you are participating in your own transformation without pretending you are the source of it.",
      "You walk, but God works.",
      "You obey, but God gives the desire.",
      "You move, but He is doing something underneath the movement.",
      "And maybe one of the clearest evidences of God working in you is not simply that your behavior changed.",
      "It is that things you once resisted are becoming things you genuinely love."
    ],
    reflection: "Where am I merely forcing myself to obey God right now, and where can I already see that He has begun changing my desires until I genuinely want what He wants?"
  },
  {
    date: "2026-09-02",
    displayDate: "September 2, 2026",
    title: "Walk in What He Prepared",
    reference: "Ephesians 2:10",
    translation: "LEB",
    verse: "For we are his creation, created in Christ Jesus for good works, which God prepared beforehand, so that we may walk in them.",
    body: [
      "‘For we are his creation.’",
      "That means even before we start talking about the work, we have to talk about the One doing the creating.",
      "God is forming something in you.",
      "And then Paul says we were created in Christ Jesus for good works which God prepared beforehand.",
      "So even the good work you walk into was not born the moment you thought of it.",
      "God was already there.",
      "He prepared the opportunity.",
      "He prepared the work.",
      "And while He was preparing the work, He was also preparing you.",
      "I think that should keep us humble.",
      "We can look back and say, ‘I helped that person. I said the right thing. I served. I gave. I showed up.’",
      "And you did.",
      "But how much of that moment was God preparing a work, shaping you for it, placing you in front of it, and then allowing you to participate in what He was already doing?",
      "Paul says we are supposed to walk in those works.",
      "You did not create the road.",
      "You were invited to walk it.",
      "And that makes ordinary obedience feel different.",
      "Somebody may encounter mercy because you walked into a work God prepared.",
      "Somebody may encounter truth because you walked into a work God prepared.",
      "Somebody may encounter patience, generosity, correction, forgiveness, or love because a person carrying the Spirit walked where God told him to walk.",
      "Christ becomes visible through people who keep walking into the things God prepared for them."
    ],
    reflection: "How many things have I called my good works that were actually God preparing a work, forming me for it, leading me to it, and then allowing me to participate in what He was already doing?"
  },
  {
    date: "2026-09-01",
    displayDate: "September 1, 2026",
    title: "Love Like Christ",
    reference: "John 13:34–35",
    translation: "LEB",
    verse: "A new commandment I give to you: that you love one another—just as I have loved you, that you also love one another. By this everyone will know that you are my disciples—if you have love for one another.",
    body: [
      "Jesus does not just tell us to love.",
      "He tells us how: ‘Just as I have loved you.’",
      "That means Christ Himself becomes the definition.",
      "We do not get to let the world define love and then bring that definition back to Jesus.",
      "We look at Jesus.",
      "He served. He forgave. He told the truth. He corrected. He had compassion. He laid His life down.",
      "And then He says, ‘Love one another like that.’",
      "I think that matters because we have been talking about Christ being visible through His people.",
      "Jesus tells you one of the clearest ways people should recognize Him in you.",
      "Love.",
      "‘By this everyone will know that you are my disciples.’",
      "Not merely because you can explain doctrine.",
      "Not merely because you know Scripture.",
      "Not merely because you call yourself a Christian.",
      "There should be something about the way you love that bears the signature of Christ.",
      "And that kind of love will sometimes require something your flesh would never choose.",
      "Forgiving when you would rather hold it.",
      "Serving when you would rather be served.",
      "Telling the truth when pretending would be easier.",
      "Being patient when you feel like you have a right to be angry.",
      "If Christ lives through you, then at some point He has to be allowed to love through you too.",
      "That may be one of the clearest ways Christ is still visible on this earth today."
    ],
    reflection: "If Christ is living through me, am I allowing Him to love people through me in ways that my natural self would not choose?"
  }
].concat(window.AJONTE_DEVOTIONALS || []);
